# Generated by Django 5.2 on 2025-04-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0002_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принято'), ('rejected', 'Отклонено'), ('revision', 'На доработке')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Опубликовано'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
