# Generated by Django 5.2 on 2025-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0003_homework_status_lecture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='description',
            field=models.TextField(max_length=50, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(max_length=50, verbose_name='Описание'),
        ),
    ]
