# Generated by Django 5.2 on 2025-04-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu', '0004_alter_homework_description_alter_lecture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
